cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    A12345:
      email: johndoe@example.com
      name: JohnDoe
      password: $2b$12$CsENWqHAhWoSPQHkXszHpuLvtKCxsyvOJhpouyHFJtzrQBsg/G2Z2
    B23456:
      email: alice.smith@example.com
      name: AliceSmith
      password: $2b$12$2Zhw/aSj/yqMPb5kc/EEJe/q7JaJZV.BS5hbJmPE1.tSkuwFpIOBO
    C34567:
      email: bobj@example.com
      name: BobJohnson
      password: $2b$12$Bweuu4pXwbmsbGUnP3CWJ.7UB0boKWaUMtvlrcA24n7lDLKQnfCHO
    D45678:
      email: emily.brown@example.com
      name: EmilyBrown
      password: $2b$12$9rsK9d.MAjI73ZZK4jNAfeTVvrOpm/e4T9c1zKg8fiDnNvOc6gRju
    E56789:
      email: michael.clark@example.com
      name: MichaelClark
      password: $2b$12$HyCnI.C0dF448Xk2CwZX1eYaS2BCFOWRA15XyM1REysDbWOl8kqL2
    F67890:
      email: sarah.lee@example.com
      name: SarahLee
      password: $2b$12$l99Vv.AlcxWfUahuIX6e8.ZobXnJKMrn3vTCYWs1RhE5yN577gauK
    G78901:
      email: david.wilson@example.com
      name: DavidWilson
      password: $2b$12$LMjTr9Rk51nRJqzIfjKUn.1sBcV6Qw.iPfzO52fvLZl2O83N9vJBq
    H89012:
      email: jennifer.taylor@example.com
      name: JenniferTaylor
      password: $2b$12$DsS5NqAxt5a8z2Dd4YSZPesDeX.y0Of.qux1cJ4xly7BC1P8/zjwy
    I90123:
      email: daniel.martinez@example.com
      name: DanielMartinez
      password: $2b$12$QZZOBvvkQemLhbXXX8Zn0Ok4T2fNG1N9iHLwQ3EKJsr8kUnol/J2y
